title: "Projeto S2C2"
logo: "/assets/images/logos2c2.png"
theme: just-the-docs

# Ajustado para GitHub Pages (raiz do domínio e subdiretório do projeto)
url: "https://leofilipe.github.io"
baseurl: "/just-docs-java-test"

# CSS customizado
just_the_docs:
  css: "assets/css/custom.css"
  
nav_external_links:
  - title: "1. INTRODUÇÃO"
    url: "#sec:01"
  - title: "2. VISÃO ARQUITETURAL"
    url: "#sec:02"
  - title: "3. MODELAGEM DO SISTEMA"
    url: "#sec:03"
  - title: "4. MODELOS DE FLUXO DO SISTEMA"
    url: "#sec:04"
  - title: "5. APLICAÇÕES DE S2C2"
    url: "#sec:05"
  - title: "6. CENÁRIOS DE TESTES E RESULTADOS"
    url: "#sec:06"
  - title: "7. PUBLICAÇÕES GERADAS"
    url: "#sec:07"
  - title: "8. CONSIDERAÇÕES FINAIS"
    url: "#sec:08"