title: "Projeto S2C2"
logo: "/assets/img/logo.png"
theme: just-the-docs

url: https://leofilipe.github.io/just-docs-java-test/

aux_links:
  Template Repository: https://leofilipe.github.io/just-docs-java-test/
