title: "Projeto S2C2"
logo: "/assets/images/logos2c2.png"
theme: just-the-docs

# URL raiz do GitHub Pages do usuário
url: "https://leofilipe.github.io"

# Nome do repositório
baseurl: "/just-docs-java-test"

# CSS customizado
just_the_docs:
  css: "assets/css/custom.css"

# LINKS NO TOPO (opcional)
nav_external_links:
  - title: "INTRODUÇÃO"
    url: "/just-docs-java-test/#sec-01"
  - title: "VISÃO ARQUITETURAL"
    url: "/just-docs-java-test/#sec-02"
  - title: "MODELAGEM DO SISTEMA"
    url: "/just-docs-java-test/#sec-03"
  - title: "MODELOS DE FLUXO DO SISTEMA"
    url: "/just-docs-java-test/#sec-04"
  - title: "APLICAÇÕES DE S2C2"
    url: "/just-docs-java-test/#sec-05"
  - title: "CENÁRIOS DE TESTES E RESULTADOS"
    url: "/just-docs-java-test/#sec-06"
  - title: "PUBLICAÇÕES GERADAS"
    url: "/just-docs-java-test/#sec-07"
  - title: "CONSIDERAÇÕES FINAIS"
    url: "/just-docs-java-test/#sec-08"
