title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://leofilipe.github.io/just-docs-java-test/

aux_links:
  Template Repository: https://leofilipe.github.io/just-docs-java-test/
