title: "Projeto S2C2"
logo: "/assets/img/logos2c2.png"
theme: just-the-docs

url: https://leofilipe.github.io/just-docs-java-test/

aux_links:
  Template Repository: https://leofilipe.github.io/just-docs-java-test/

# adiciona seu CSS customizado
just_the_docs:
  css: "assets/css/custom.css"
