# Arquivo: _config.yml

title: "Projeto S2C2"
logo: "/assets/images/logos2c2.png"
theme: just-the-docs

# IMPORTANTE: A URL deve ser a RAIZ do seu domínio de usuário/organização
url: "https://leofilipe.github.io"

# IMPORTANTE: O baseurl deve ser o nome do seu repositório,
# começando com barra (/) e SEM barra no final
baseurl: "/just-docs-java-test"

# CSS customizado
just_the_docs:
  css: "assets/css/custom.css"
  
 nav:
  - title: "INTRODUÇÃO"
    url: "{{ site.baseurl }}/#sec-01"

  - title: "VISÃO ARQUITETURAL"
    url: "{{ site.baseurl }}/#sec-02"

  - title: "MODELAGEM DO SISTEMA"
    url: "{{ site.baseurl }}/#sec-03"
  
  - title: "MODELOS DE FLUXO DO SISTEMA"
    url: "{{ site.baseurl }}/#sec-04"
    
  - title: "APLICAÇÕES DE S2C2"
    url: "{{ site.baseurl }}/#sec-05"
    
  - title: "CENÁRIOS DE TESTES E RESULTADOS"
    url: "{{ site.baseurl }}/#sec-06"
    
  - title: "PUBLICAÇÕES GERADAS"
    url: "{{ site.baseurl }}/#sec-07"
    
  - title: "CONSIDERAÇÕES FINAIS"
    url: "{{ site.baseurl }}/#sec-08"