# Arquivo: _config.yml

title: "Projeto S2C2"
logo: "/assets/images/logos2c2.png"
theme: just-the-docs

# IMPORTANTE: A URL deve ser a RAIZ do seu domínio de usuário/organização
url: "https://leofilipe.github.io"

# IMPORTANTE: O baseurl deve ser o nome do seu repositório,
# começando com barra (/) e SEM barra no final
baseurl: "/just-docs-java-test"

# CSS customizado
just_the_docs:
  css: "assets/css/custom.css"